### ISSUE TITLE
Branch Jobs generated incorrectly

### ISSUE THREAD

**Issue by nllarson** [jenkinsci/seed-plugin#20]
I have a seed job configured like this:

Seed YAML:

```
http-enabled: no
github-enabled: no
bitbucket-enabled: yes
projects:
   - id: "client/application-api"
     name: "application-api"
```

Seed Job Config:

<img width="1166" alt="screen shot 2016-01-22 at 7 42 36 am" src="https://cloud.githubusercontent.com/assets/208498/12512130/0050035a-c0dc-11e5-88dc-1dea1cf64289.png">

And

<img width="1183" alt="screen shot 2016-01-22 at 7 42 51 am" src="https://cloud.githubusercontent.com/assets/208498/12512131/05365f86-c0dc-11e5-8147-ecba31ea621f.png">

I then run the seed with these params:

Project Id: client/application-api
SCM Url: https://bitbucket.com/client/application-api.git
SCM Creds:  (selected from dropdown)

It generates a Project folder and Project Seed.  It looks fine, it takes a parameter of a BRANCH name.

<img width="1095" alt="screen shot 2016-01-22 at 7 49 58 am" src="https://cloud.githubusercontent.com/assets/208498/12512250/c65268ae-c0dc-11e5-8d86-11cf1c6c9948.png">

![projectseeed](https://cloud.githubusercontent.com/assets/208498/12512236/b48d6cf4-c0dc-11e5-929c-759964194783.gif)

From here is where I am kind of confused.  I can't get the build to pick up PUSHES unless I manually start the Branch Seed for one of my branches. (Is this the correct way?)  I manually start the `application-api-seed` job, enter a branch name of 'develop' and let it do its thing.  It generates the `application-api-develop` folder and seed.  But the jobs that are created from my `seed.groovy` file are not created.  Here is that error.

<img width="644" alt="screen shot 2016-01-22 at 7 56 16 am" src="https://cloud.githubusercontent.com/assets/208498/12512510/63b8d686-c0de-11e5-99cb-a9f40bd48a41.png">

I looked at your Jenkins instance and noticed that the `Inject Environment Variables...` option is selected and populated on your Branch Seed job.  (like this:)

<img width="1114" alt="screen shot 2016-01-22 at 7 57 25 am" src="https://cloud.githubusercontent.com/assets/208498/12512523/6f1a1544-c0de-11e5-8328-6cfd05f189b3.png">

If I copy these properties to my config (but with my correct values) things seem to work, but I am fairly sure I shouldn't have to do that for each branch for each project.

I am using Jenkins 1.643 and Seed-Plugin 0.18.0

**Comment by dcoraboeuf** [comment]
Hi Nick,

Is it possible to post part of your `seed.groovy` file, at least around the line in error (line 22)? Because you're right, the `BRANCH` is normally injected as a variable and your `seed.groovy` should not fail on this.

Damien

**Comment by dcoraboeuf** [comment]
Is the `envInject` plugin installed? If not, this is a requirement for the seed plugin, and it might be missing in the list of dependencies?

**Comment by dcoraboeuf** [comment]
I confirm that `envinject` is not currently a dependency of the seed plugin, meaning that it was probably not installed.

I'll fix this soon for the 0.19.

In the meantime, as a workaround, you can install the [envinject plugin](https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin) yourself. You might have to regenerate your branch folder though.

Thanks for the issue!
Damien

**Comment by nllarson** [comment]
I basically copied the seed.groovy from the versioning project.  

<img width="957" alt="screen shot 2016-01-22 at 10 27 29 am" src="https://cloud.githubusercontent.com/assets/208498/12516381/cac0000c-c0f2-11e5-897c-900a6ac5ac9b.png">

And the Environment Injector plugin is there.

![screen shot 2016-01-22 at 10 26 09 am](https://cloud.githubusercontent.com/assets/208498/12516351/a66a5ad6-c0f2-11e5-829a-4e23e69bf62d.png)

**Comment by dcoraboeuf** [comment]
If I understand correctly, your issue boils down to the fact that the following configuration, with your own settings of course:

<img width="1114" alt="screen shot 2016-01-22 at 7 57 25 am" src="https://cloud.githubusercontent.com/assets/208498/12512523/6f1a1544-c0de-11e5-8328-6cfd05f189b3.png">

is not present in the seed job of your branch folder, even if the envinject plugin is installed correctly.

If you extract the `config.xml` of your job, if the environment section correctly generated? For example, for the `nemerosa/versioning` sample, the corresponding XML is:

```xml
<buildWrappers>
        <EnvInjectBuildWrapper>
            <info>
                <propertiesContent>PROJECT=nemerosa/versioning
PROJECT_CLASS=
PROJECT_SCM_TYPE=git
PROJECT_SCM_URL=https://github.com/nemerosa/versioning
PROJECT_SCM_CREDENTIALS=
BRANCH=master
SEED_PROJECT=versioning
SEED_BRANCH=master</propertiesContent>
                <loadFilesFromMaster>false</loadFilesFromMaster>
            </info>
        </EnvInjectBuildWrapper>
    </buildWrappers>
```

**Comment by dcoraboeuf** [comment]
If this is present, but nothing is displayed, it might be a conflict version.

**Comment by nllarson** [comment]
That must be my issue.  I do see those lines in my config.xml.  So a plugin version conflict with the envInject plugin?  Thanks for your help so far btw!

**Comment by nllarson** [comment]
I've also noticed this in my Jenkins Config 'Manage Old Data'  So something about the way the job generation is working isn't quite right when it comes to the xml. 

hudson.model.FreeStyleProject	application-api/application-api-release-0.6.5/application-api-release-0.6.5-build	CannotResolveClassException: au.com.centrumsystems.hudson.plugin.buildpipeline.trigger.BuildPipelineTrigger


hudson.model.FreeStyleProject	application-api/application-api-release-0.6.5/application-api-release-0.6.5-build	CannotResolveClassException: EnvInjectBuildWrapper

**Comment by nllarson** [comment]
I then created a new job by hand, and put in some 'Injected Properties', the config.xml for those looked like this:

```  <buildWrappers>
    <EnvInjectBuildWrapper plugin="envinject@1.92.1">
      <info>
        <propertiesContent>FOO=bar
WACKA=wacka</propertiesContent>
        <loadFilesFromMaster>false</loadFilesFromMaster>
      </info>
    </EnvInjectBuildWrapper>
  </buildWrappers>
```

Where the generated job's config.xml looked like this:

```
      <buildWrappers>
        <EnvInjectBuildWrapper>
            <info>
                <propertiesContent>PROJECT=client/application-api
PROJECT_CLASS=
PROJECT_SCM_TYPE=git
PROJECT_SCM_URL=https://bitbucket.org/client/application-api.git
PROJECT_SCM_CREDENTIALS=UUID-1234
BRANCH=develop
SEED_PROJECT=application-api
SEED_BRANCH=develop</propertiesContent>
                <loadFilesFromMaster>false</loadFilesFromMaster>
            </info>
        </EnvInjectBuildWrapper>
        <EnvInjectPasswordWrapper>
            <injectGlobalPasswords>true</injectGlobalPasswords>
            <passwordEntries/>
        </EnvInjectPasswordWrapper>
    </buildWrappers>
```

**Comment by dcoraboeuf** [comment]
Hi Nick,

I've upgraded the seed plugin to use the latest version of the `envinject` plugin (1.92.1). No problem so far.

Have you had a look in Jenkins log files to see if you had an error linked to the generation of your job?

Thanks,
Damien.

**Comment by nllarson** [comment]
Damien,

Thanks, I'll give the new version a look in the morning. I'll give the logs a look too.  Thanks again!
