### ISSUE TITLE
Seed.groovy location option required

### ISSUE THREAD

**Issue by sergeyshepel** [jenkinsci/seed-plugin#27]
There is no option in the plugin to specify the location for groovy script if you want to put it not in seed folder.

**Comment by dcoraboeuf** [comment]
There used to be an option in early 0.x versions, but I have removed it in versions 1.0 / 2.0.

In which way would you use it?

Thanks,
Damien.

**Comment by sergeyshepel** [comment]
For example, if you have project structure which been approved and could not be changed.
In this case you need to put all your scripts in:
<project>/src/main/groovy/seed.groovy

**Comment by dcoraboeuf** [comment]
If you put `seed.groovy` in `src/main/groovy` it might be considered a project source file, compiled as such and giving compilation errors. Unless you exclude it in your build files, but this gives extra configuration work, no? That's why a location outside of the main source code makes more sense to me, either in a separate folder (like `seed`) or at the root of the project.

**Comment by sergeyshepel** [comment]
I think you are right, it it was just an example, also I believe that it's always good when you have an option;)

**Comment by dcoraboeuf** [comment]
I'll think about it. Ok to do this in version 2.x ?

**Comment by sergeyshepel** [comment]
Ok, sounds good! Many thanks for considering my request!

**Comment by dcoraboeuf** [comment]
There are actually two locations to consider:

* the `seed.properties` file for pipelines defined using fully or part of a pipeline library
* the `seed.groovy` file for pipelines defined using directly a DSL (with or without a pipeline library)

I'll just make the folder containing those one or two files configurable.

**Comment by sergeyshepel** [comment]
Thanks a lot, @dcoraboeuf!

**Comment by dcoraboeuf** [comment]
Not ready yet. Still need to create some integration tests, to document and to release. Should be available end of September.

**Comment by sergeyshepel** [comment]
Np, anyway it's a good news for me that you decided to bring this option back!

**Comment by dcoraboeuf** [comment]
Tests failing in Jenkins, not locally. I will investigate before releasing.

**Comment by dcoraboeuf** [comment]
Available in 2.1.1. See documentation at https://github.com/jenkinsci/seed-plugin/wiki/Configuration (Script directory).

**Comment by sergeyshepel** [comment]
@dcoraboeuf  sorry for the late reply, but thanks a lot for this quick integration of this issue!
